[package]
name = "flavorapp"
version = "0.1.0"
description = "FlavorTown, in a desktop App"
authors = ["KodeurKubik <kubik@openvoxel.studio>"]
edition = "2024"

[lib]
name = "flavorapp_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false }
tauri-plugin-opener = "2"
tauri-plugin-http = "2"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
